apiVersion: ve1
kind: PersistentVolume
metadata:
  name: mysqlpv
spec:
  storageClassName: dbpv
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"